config/routes.rb
Rails.application.routes.draw do
  # for debugging only: 
  resources :favourites
 
  devise_for :users

  get 'checkfavourites', to: 'favourites#checkfavourites'

  # main routes
  root 'home#homepage'
  get 'about', to: 'home#about'
  get 'categories', to: 'home#categories'
  get 'leaderboard', to: 'home#leaderboard'
  get 'favouritespage', to: 'home#favouritespage'
  get 'mealpage/:recipe_id', to: 'home#mealpage', as: 'mealpage'

  # categories
  get 'paleo/:page_number', to: 'home#paleo', as: 'paleo'
  get 'vegan/:page_number', to: 'home#vegan', as: 'vegan'
  get 'vegetarian/:page_number', to: 'home#vegetarian', as: 'vegetarian'
  get 'pescatarian/:page_number', to: 'home#pescatarian', as: 'pescatarian'

  # route for adding a favourite for the current user
  put 'mealpage/:recipe_id/favourite', to: 'favourites#addfavourite', as: 'addfavourite'
  # and for removing
  put 'mealpage/:recipe_id/favouriteremove', to: 'favourites#removefavourite', as: 'removefavourite'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user



end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController 
  include ActionController::Live
  include FavouritesHelper

  before_action :set_favourite, only: %i[ show edit update destroy ]

  def addfavourite
    Favourite.create(user_id: current_user.id, recipe: params[:recipe_id])
    redirect_to mealpage_path(params[:recipe_id])
  end

  def removefavourite
    Favourite.find_by(user: current_user, recipe: params[:recipe_id]).destroy
    redirect_to mealpage_path(params[:recipe_id])
  end


  # for updating the leaderboard live
  def checkfavourites
    response.headers['Content-Type'] = 'text/event-stream'
    sse = SSE.new(response.stream, retry: 10000, event: "checkfavourites")

    # now convert favourites to JSON
    leaderboard = get_leaderboard()
    # convert to string
    leaderboard_string = ''
    leaderboard.each do |recipe|
      leaderboard_string += recipe[0].to_s
      leaderboard_string += ':'
      leaderboard_string += recipe[1].to_s
      leaderboard_string += ','
    end

    puts leaderboard_string

    sse.write({result: leaderboard_string})
    

  ensure
    response.stream.close
  end


  



  # GET /favourites or /favourites.json
  def index
    @favourites = Favourite.all
  end

  # GET /favourites/1 or /favourites/1.json
  def show
  end

  # GET /favourites/new
  def new
    @favourite = Favourite.new
  end

  # GET /favourites/1/edit
  def edit
  end

  # POST /favourites or /favourites.json
  def create
    @favourite = Favourite.new(favourite_params)

    respond_to do |format|
      if @favourite.save

        
        
        format.html { redirect_to favourite_url(@favourite), notice: "Favourite was successfully created." }
        format.json { render :show, status: :created, location: @favourite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourites/1 or /favourites/1.json
  def update
    respond_to do |format|
      if @favourite.update(favourite_params)
        format.html { redirect_to favourite_url(@favourite), notice: "Favourite was successfully updated." }
        format.json { render :show, status: :ok, location: @favourite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1 or /favourites/1.json
  def destroy
    
    @favourite.destroy

    respond_to do |format|
      format.html { redirect_to favouritespage_path, notice: "Favourite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favourite_params
      params.require(:favourite).permit(:recipe, :user_id)
    end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
    def favourite_exists(user, recipe_id)
        result = false
        Favourite.all.each do |f|
          if f.user.email === user.email && f.recipe === recipe_id
            result = true
          end
        end

        return result
    end

    # returns a hash mapping recipe ID to number of times it has been favourited
    # sorted in descending order
    def get_leaderboard()
      favourites = {}
      Favourite.all.each do |favourite|
        if favourites[favourite.recipe] == nil
          favourites[favourite.recipe] = 1
        else
          favourites[favourite.recipe] += 1
        end
      end
      favourites_sorted = favourites.sort_by { |recipe, freq | -freq }
      return favourites_sorted
    end


end

app/views/favourites/_form.html.erb
<%= form_with(model: favourite, local: true) do |form| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% favourite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe %>
    <%= form.number_field :recipe %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favourites</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favourites.each do |favourite| %>
      <tr>
        <td><%= favourite.recipe %></td>
        <td><%= favourite.user.email %></td>
        <td><%= link_to 'Show', favourite %></td>
        <td><%= link_to 'Edit', edit_favourite_path(favourite) %></td>
        <td><%= link_to 'Destroy', favourite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favourite', new_favourite_path %>

app/views/favourites/new.html.erb
<h1>New Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/show.html.erb
<p>
  <strong>Recipe:</strong>
  <%= @favourite.recipe %>
</p>

<p>
  <strong>User:</strong>
  <%= @favourite.user %>
</p>

<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>