config/routes.rb
Rails.application.routes.draw do
  # for debugging only: 
  resources :favourites
 
  devise_for :users

  get 'checkfavourites', to: 'favourites#checkfavourites'

  # main routes
  root 'home#homepage'
  get 'about', to: 'home#about'
  get 'categories', to: 'home#categories'
  get 'leaderboard', to: 'home#leaderboard'
  get 'favouritespage', to: 'home#favouritespage'
  get 'mealpage/:recipe_id', to: 'home#mealpage', as: 'mealpage'

  # categories
  get 'paleo/:page_number', to: 'home#paleo', as: 'paleo'
  get 'vegan/:page_number', to: 'home#vegan', as: 'vegan'
  get 'vegetarian/:page_number', to: 'home#vegetarian', as: 'vegetarian'
  get 'pescatarian/:page_number', to: 'home#pescatarian', as: 'pescatarian'

  # route for adding a favourite for the current user
  put 'mealpage/:recipe_id/favourite', to: 'favourites#addfavourite', as: 'addfavourite'
  # and for removing
  put 'mealpage/:recipe_id/favouriteremove', to: 'favourites#removefavourite', as: 'removefavourite'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alert.html.erb
<%# New view for alerts %>
<div class="alert alert-dark alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_footer.html.erb
<!-- had to remove the Bootstrap class on the footer because it made the footer block other content -->
<footer>
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><%= link_to 'Home', root_path, class:"nav-link px-2 text-muted" %></li>
      <li class="nav-item"><%= link_to 'Browse Meals', categories_path, class:"nav-link px-2 text-muted" %></li>
      <li class="nav-item"><%= link_to 'Leaderboard', leaderboard_path, class:"nav-link px-2 text-muted" %>   </li>
      <li class="nav-item"><%= link_to 'About us', 'about', class:"nav-link px-2 text-muted" %></li>
    </ul>
    <p class="text-center text-muted">Team 15</p>
  </footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    
    <%= link_to 'GoodieFoodie', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'Browse Meals', categories_path, class:"nav-link" %>                   
        </li>

        <li class="nav-item">
          <%= link_to 'Leaderboard', leaderboard_path, class:"nav-link" %>         
        </li>

        <% if user_signed_in? %>
          <li class='nav-item'><%= link_to 'Favourites', favouritespage_path, class:"nav-link" %> </li><!-- need path/route -->
        <%end%>

        <li class="nav-item">
          <%= link_to 'About us', about_path, class:"nav-link" %>
        </li>
      

        

        </ul>

      <% if user_signed_in? %>
          <span class="navbar-text fst-italic mx-2">
            <%= current_user.email %>
          </span>
          <li class="nav-item mx-2">
  			      <%= link_to 'Edit profile', edit_user_registration_path, class:"btn btn-outline-primary" %>
  		    </li>
          
        <%end%>

      <form class="d-flex mx-2">
        <!-- If user is signed in, he will be able to see Sign out option -->
        <% if user_signed_in? %>
	       <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:"btn btn-outline-danger" %>

        <% else %>
        <!-- If user is not signed in, he will be able to see Sign up and Log in options -->
	       <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-outline-success" %>
	       <%= " / " %>
	       <%= link_to 'Log in', new_user_session_path, class:"btn btn-outline-primary" %>
        <% end %>

        
      </form>

      
     
    
      
    </div>
  </div>
</nav>
    
  




<!-- flash messages -->
<%flash.each do |key, value|%> 
<%  content_tag :div, content_tag(:p, value), id: '#{key}' unless value.blank?%> 
<%end%>