config/routes.rb
Rails.application.routes.draw do
  # for debugging only: 
  resources :favourites
 
  devise_for :users

  get 'checkfavourites', to: 'favourites#checkfavourites'

  # main routes
  root 'home#homepage'
  get 'about', to: 'home#about'
  get 'categories', to: 'home#categories'
  get 'leaderboard', to: 'home#leaderboard'
  get 'favouritespage', to: 'home#favouritespage'
  get 'mealpage/:recipe_id', to: 'home#mealpage', as: 'mealpage'

  # categories
  get 'paleo/:page_number', to: 'home#paleo', as: 'paleo'
  get 'vegan/:page_number', to: 'home#vegan', as: 'vegan'
  get 'vegetarian/:page_number', to: 'home#vegetarian', as: 'vegetarian'
  get 'pescatarian/:page_number', to: 'home#pescatarian', as: 'pescatarian'

  # route for adding a favourite for the current user
  put 'mealpage/:recipe_id/favourite', to: 'favourites#addfavourite', as: 'addfavourite'
  # and for removing
  put 'mealpage/:recipe_id/favouriteremove', to: 'favourites#removefavourite', as: 'removefavourite'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include SpoonacularHelper
  include ActionController::Live
  #Home controller

  #def testing
  #  response.headers['Content-Type'] = 'text/event-stream'
  #  sse = SSE.new(response.stream, retry: 3000, event: "testing")
  #  sse.write({ value: 1 })
  #ensure
  #  response.stream.close
  #end


  def homepage
  end

  def about
  end

  def categories
  end
  
  def favouritespage
    @favourites = Favourite.all
  end

  def leaderboard
    @favourites = Favourite.all
  end

  def mealpage
    @recipe = getRecipeById(params[:recipe_id])
  end

  def show
  end

  def paleo
    @page_number = params[:page_number]
  end

  def vegan
    @page_number = params[:page_number]
  end

  def vegetarian
    @page_number = params[:page_number]
  end

  def pescatarian
    @page_number = params[:page_number]
  end

  
  


  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>About us page</h1>
  <h6>Team 15</h6>

app/views/home/categories.html.erb
<h1>Categories</h1>
  <!-- CARDS FOR DIFFERENT MEAL CATEGORIES -->
<div class="row g-5">
          
  <div class="card border-3 bg-dark w-50">                    <!-- CARD INSIDE OF CONTAINER -->
    <!--image for category-->
    <%=image_tag("paleo.png", :alt => "paleo image")%>
    <div class="card-body">
      <!-- category title-->
      <h3 class="card-title fw-bolder text-light">Paleo</h3>
      <!-- Button to view more meals of this category -->
        <%=link_to "View meals", paleo_path(1), class:"btn btn-success btn-lg"%>     
      <div class="card-body text-light">
        <!-- brief description of category -->
        <p class="card-text">A paleo diet typically includes lean meats, fish, fruits, vegetables, nuts and seeds — foods that in the past could be obtained by hunting and gathering. A paleo diet limits foods that became common when farming emerged about 10,000 years ago.</p>
        <!-- description via https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/in-depth/paleo-diet/art-20111182-->
      </div>
    </div> 
  </div>

  <div class="card border-3 bg-dark w-50">                    <!-- CARD INSIDE OF CONTAINER -->
    <!--image for category-->
    <%=image_tag("vegan.png", :alt => "vegan image")%>
    <div class="card-body">
      <!-- category title-->
      <h3 class="card-title fw-bolder text-light">Vegan</h3>
      <!-- Button to view more meals of this category -->
        <%=link_to "View meals", vegan_path(1), class:"btn btn-success btn-lg"%>     
      <div class="card-body text-light">
        <!-- brief description of category -->
        <p class="card-text">A vegan diet contains only plants (such as vegetables, grains, nuts and fruits) and foods made from plants. Vegans do not eat foods that come from animals, including dairy products and eggs.</p>
        <!-- description via https://www.nhs.uk/live-well/eat-well/how-to-eat-a-balanced-diet/the-vegan-diet/-->
      </div>
    </div> 
  </div>

  <div class="card border-3 bg-dark w-50">                    <!-- CARD INSIDE OF CONTAINER -->
    <!--image for category-->
    <%=image_tag("vegiterian.png", :alt => "vegetarian image")%>
    <div class="card-body">
      <!-- category title-->
      <h3 class="card-title fw-bolder text-light">Vegetarian</h3>
      <!-- Button to view more meals of this category -->
        <%=link_to "View meals", vegetarian_path(1), class:"btn btn-success btn-lg"%>     
      <div class="card-body text-light">
        <!-- brief description of category -->
        <p class="card-text">The vegetarian diet involves abstaining from eating meat, fish and poultry.</p>
      </div>
    </div> 
  </div>

  <div class="card border-3 bg-dark w-50">                    <!-- CARD INSIDE OF CONTAINER -->
    <!--image for category-->
    <%=image_tag("pescatarian.png", :alt => "fish image")%>
    <div class="card-body">
      <!-- category title-->
      <h3 class="card-title fw-bolder text-light">Pescatarian</h3>
      <!-- Button to view more meals of this category -->
        <%=link_to "View meals", pescatarian_path(1), class:"btn btn-success btn-lg"%>     
      <div class="card-body text-light">
        <!-- brief description of category -->
        <p class="card-text">A pescatarian diet typically includes vegetables, grains and pulses along with fish and other seafood, but generally excludes meat and sometimes dairy.</p>
        <!-- description via https://www.bbcgoodfood.com/howto/guide/what-pescatarian-diet -->
      </div>
    </div> 
  </div>

</div>

app/views/home/favouritespage.html.erb
<!-- loops through favourites table and looks for the ones that match the current user -->
<!-- generates a card for each of these -->
<h1>Favourites</h1>
<%favourites = @favourites%>
<% favourites.each do |favourite| %>
  <%if favourite.user.email === current_user.email %>
    <% recipe = getRecipeById(favourite.recipe)%>
    <div class="col-3 my-3">                                   <!-- Column of 12 divided into sections of 3 for each food card-->
      <div class="card border-3 bg-secondary rounded shadow border-3" style="width:275">                    <!-- CARD INSIDE OF CONTAINER  -->
        <%=image_tag(recipe['image'], :class => "card-img-top", :alt => "recipe_img")%>           <!-- IMAGE INSIDE CARD -->
        <div class="card-body">
          <h5 class="card-title fw-bolder text-light"><%=recipe['title']%></h5>                      <!-- Name of the meal -->
          <%=link_to "View recipe", mealpage_path(recipe['id']), class:"btn btn-primary btn shadow-sm"  %>
          <%= link_to 'Remove', favourite, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        </div>
      </div>
    </div>
  <%end%>
<%end%>    

app/views/home/homepage.html.erb
<!-- Intro text and image -->
<section id="intro">
  <div class="container-lg">
    <div class="row justify-content-center align-items-center">
      <div class="col-md-5 text-center text-md-start">   <!-- Default sized screen text is in the center then as the screen gets larger it will be moved to the left -->
        <h1>
          <div class="display-2">Goodie Foodie </div>
          <div class="display-5">Your journey begins here</div>
        </h1>
        <% if user_signed_in? %>
          <%= link_to 'Browse meals', categories_path, class:"btn btn-success btn-lg" %>
        <% else %>
          <%= link_to 'Sign up for free!', new_user_registration_path, class:"btn btn-secondary btn-lg" %>
        <% end %>
      </div>
      <div class="col-md-5 text-center d-none d-md-block">
        <!--previous class: img-fluid-->
        <%=image_tag("meal-image.jpg", :alt => 'meal image')%>
      </div>
    </div>
  </div>
</section>

app/views/home/leaderboard.html.erb
<div class='container'>
<div id='leaderboard'>
</div>
</div>

app/views/home/leaderboard_old.html.erb
<div class="container">
  <!-- gets sorted map of recipe IDs to number of times they've been favourited -->
  <% leaderboard = get_leaderboard() %>

  <h1>Leaderboard</h1>
  <% n = 1 %>
  <% leaderboard.each do |recipe| %>
    
    <!-- get recipe details from Spoonacular -->
    <% recipe_details = getRecipeById(recipe[0]) %>
    
    <div class="my-5 mx-3 ">
      <!-- DISECTING PAGE INTO ROW WITH SPACE BETWEEN MARGIN OF 5-->
      <div class="row my-5">                    
        <!-- CREATING FIRST COLUMN SPECIFIED WITH 1 WIDTH-->        
        <div class="col-1">                                                  
          <div class="bg-secondary p-4 text-center rounded shadow-lg text-light fs-2 fw-bold" > <%=n%>
          </div>
        </div>
        <!-- CREATING SECOND COLUMN SPECIFIED WITH 1 WIDTH-->
        <div class="col-4">                                            
          <!-- For Creating card for the image of the meal -->   
          <div class="bg-secondary p-4 text-center rounded shadow-lg">    
            <!-- CARD INSIDE OF CONTAINER  -->            
            <div class="card border-3 bg-dark p-2" style='height:350px'>               
              <!-- IMAGE INSIDE CARD -->    
              <%=image_tag(recipe_details['image']) %>            
              <div class="card-body">
                <h5 class="card-title fw-bolder text-light"><%=recipe_details['title']%></h5>
                <%=link_to 'View recipe', mealpage_path(recipe[0]), class:'btn btn-primary btn'%>
              </div>
            </div>
          </div>
        </div>
        <!-- CREATING THIRD COLUMN SPECIFIED WITH 7 WIDTH TO CONTAIN TABLE--> 
        <div class="col-7">                                              
          <div class="bg-secondary p-4 rounded shadow-lg">

            <!-- stats table -->
            <!-- nutrients can be found under nutrition => nutrients -->
            <!-- 0-Calories 1-Fat 3-Carbs 8-Protein -->
            <div class="card border-3 bg-dark p-2" style='height:350px'>  
              <table class='table table-dark fs-5 align-middle' style='height:300px'>
                <tr>
                  <th>Favourites</th>
                  <td><%=recipe[1]%></td>
                </tr>
                <tr>
                  <th>Calories</th>
                  <td class='align-middle'>
                    <%=recipe_details['nutrition']['nutrients'][0]['amount']%>
                    <%=recipe_details['nutrition']['nutrients'][0]['unit']%>
                  </td>
                </tr>
                <tr>
                  <th>Protein</th>
                  <td class='align-middle'>
                    <%=recipe_details['nutrition']['nutrients'][8]['amount']%>
                    <%=recipe_details['nutrition']['nutrients'][8]['unit']%>
                  </td>
                </tr>
                <tr>
                  <th>Fat</th>
                  <td class='align-middle'>
                    <%=recipe_details['nutrition']['nutrients'][1]['amount']%>
                    <%=recipe_details['nutrition']['nutrients'][1]['unit']%>
                  </td>
                </tr>
                <tr>
                  <th>Carbs</th>
                  <td>
                    <%=recipe_details['nutrition']['nutrients'][3]['amount']%>
                    <%=recipe_details['nutrition']['nutrients'][3]['unit']%>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%n+=1%>
  <%end%>
</div>  

app/views/home/mealpage.html.erb
  
  <div class="container">
    <!--<button type="button" class="btn btn-outline-danger my-2">Favourite</button>   Button to favourite meal-->
    <%if user_signed_in? %>
        <%if favourite_exists(current_user, @recipe['id'])%>
            <%=button_to 'Remove favourite', removefavourite_path(@recipe['id']), method: 'put', class: "btn btn-danger my-2" %>
        <%else%>
            <%=button_to 'Favourite', addfavourite_path(@recipe['id']), method: 'put', class: "btn btn-success my-2"%>
        <%end%>
    <%end%>
    <button type="button" class="btn btn-outline-info my-2 mx-1">Share</button>   <!-- Button to share meal via twitter-->

    <% recipe_img = @recipe['image'] %>
    
    

    <!-- Name of the meal-->
    <h1 class="display-3 text-centre"> <%=@recipe['title']%> </h1>

    <div class="row my-2">
        <div class="col-6 ">
            <!-- Image for the meal-->
            <div class="card border-3 bg-dark w-50 shadow-sm" >
                <%= image_tag "#{recipe_img}", class:"card-img-top"%>
            </div>

        </div>

        <div class="col-6">
            <!-- Description of meal-->
            <p class="text"> <%=removeTags(@recipe['summary'].html_safe) %> 
            </p>      

            <!-- Cost and the time to cook the meal [included in description]-->
            <!--<p class="h6">Cost:</p>-->
            <!--<p class="h6">Time:</p>-->
        </div>

        <!-- Page divider-->
        <hr class="mt-4 mb-4">

    </div>


    <div class="row my-2">

        <div class="col-6 ">

            <!-- Meal Instructions-->
            <h3>Instructions</h3>
            <%=removeTags(@recipe['instructions'])%>

        </div> 

        <div class="col-6 ">

            <h3>Ingredients</h3>

            <%@recipe['extendedIngredients'].each do |ingredient|%>
                <%=removeTags(ingredient['original'])%>
                <br>
            <%end%>
            
        </div> 
        

        <hr class="mt-4 mb-3">

        <!-- equipment if necessary... 
        <div class="col-6">

            <h3>Equipment</h3>

           
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam error obcaecati incidunt. Aspernatur aliquid dolore maxime aut. Voluptatibus necessitatibus quod,
                 veritatis vero labore libero est eveniet, ea, maxime quas ipsum error impedit reprehenderit! Sapiente accusamus nesciunt ipsa quae iusto suscipit.
                 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam error obcaecati incidunt. Aspernatur aliquid dolore maxime aut. Voluptatibus necessitatibus quod,
                 veritatis vero labore libero est eveniet, ea, maxime quas ipsum error impedit reprehenderit! Sapiente accusamus nesciunt ipsa quae iusto suscipit.
                 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam error obcaecati incidunt. Aspernatur aliquid dolore maxime aut. Voluptatibus necessitatibus quod,
                 veritatis vero labore libero est eveniet, ea, maxime quas ipsum error impedit reprehenderit! Sapiente accusamus nesciunt ipsa quae iusto suscipit.
                 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam error obcaecati incidunt. Aspernatur aliquid dolore maxime aut. Voluptatibus necessitatibus quod,
                 veritatis vero labore libero est eveniet, ea, maxime quas ipsum error impedit reprehenderit! Sapiente accusamus nesciunt ipsa quae iusto suscipit.
            </p>
            
        </div> 
        -->

    </div>

  </div>

app/views/home/paleo.html.erb
<h1>Paleo</h1>
<div class="row my-4">
<!-- get appropiate recipes via API request -->
    <% results = getRecipesByDiet(8, @page_number.to_i, 'paleo')%>
    <% recipes = results['results']%>
    <!-- loop through them and produce a card for each -->
    <!-- currently 8 meals displayed in 2 rows and 4 columns -->
    <% recipes.each do |recipe| %>
        <div class="col-3 my-3">                                   <!-- Column of 12 divided into sections of 3 for each food card-->
            <div class="card border-3 bg-secondary rounded shadow border-3" style="width:275">                    <!-- CARD INSIDE OF CONTAINER  -->
                <%=image_tag(recipe['image'], :class => "card-img-top", :alt => "recipe_img")%>           <!-- IMAGE INSIDE CARD -->
                <div class="card-body">
                <h5 class="card-title fw-bolder text-light"><%=recipe['title']%></h5>                      <!-- Name of the meal -->
                <%=link_to "View recipe", mealpage_path(recipe['id']), class:"btn btn-primary btn shadow-sm"  %>                  <!-- Button link that leads you to the meal -->
                </div>
            </div>
        </div>
    <%end%>
</div>

<ul class="pagination">
    <li class="page-item">
        <%=link_to 'Previous page', paleo_path(@page_number.to_i - 1), class: "page-link"%>
    </li>
    <li class="page-item">
        <%=link_to 'Next page', paleo_path(@page_number.to_i + 1), class: "page-link"%>
    </li>
</u>

app/views/home/pescatarian.html.erb
<h1>Pescatarian</h1>
<div class="row my-4">
<!-- get appropiate recipes via API request -->
    <% results = getRecipesByDiet(8, @page_number.to_i, 'pescatarian')%>
    <% recipes = results['results']%>
    <!-- loop through them and produce a card for each -->
    <!-- currently 8 meals displayed in 2 rows and 4 columns -->
    <% recipes.each do |recipe| %>
        <div class="col-3 my-3">                                   <!-- Column of 12 divided into sections of 3 for each food card-->
            <div class="card border-3 bg-secondary rounded shadow border-3" style="width:275">                    <!-- CARD INSIDE OF CONTAINER  -->
                <%=image_tag(recipe['image'], :class => "card-img-top", :alt => "recipe_img")%>           <!-- IMAGE INSIDE CARD -->
                <div class="card-body">
                <h5 class="card-title fw-bolder text-light"><%=recipe['title']%></h5>                      <!-- Name of the meal -->
                <%=link_to "View recipe", mealpage_path(recipe['id']), class:"btn btn-primary btn shadow-sm"  %>                  <!-- Button link that leads you to the meal -->
                </div>
            </div>
        </div>
    <%end%>
</div>

<ul class="pagination">
    <li class="page-item">
        <%=link_to 'Previous page', pescatarian_path(@page_number.to_i - 1), class: "page-link"%>
    </li>
    <li class="page-item">
        <%=link_to 'Next page', pescatarian_path(@page_number.to_i + 1), class: "page-link"%>
    </li>
</u>

app/views/home/vegan.html.erb
<h1>Vegan</h1>
<div class="row my-4">
<!-- get appropiate recipes via API request -->
    <% results = getRecipesByDiet(8, @page_number.to_i, 'vegan')%>
    <% recipes = results['results']%>
    <!-- loop through them and produce a card for each -->
    <!-- currently 8 meals displayed in 2 rows and 4 columns -->
    <% recipes.each do |recipe| %>
        <div class="col-3 my-3">                                   <!-- Column of 12 divided into sections of 3 for each food card-->
            <div class="card border-3 bg-secondary rounded shadow border-3" style="width:275">                    <!-- CARD INSIDE OF CONTAINER  -->
                <%=image_tag(recipe['image'], :class => "card-img-top", :alt => "recipe_img")%>           <!-- IMAGE INSIDE CARD -->
                <div class="card-body">
                <h5 class="card-title fw-bolder text-light"><%=recipe['title']%></h5>                      <!-- Name of the meal -->
                <%=link_to "View recipe", mealpage_path(recipe['id']), class:"btn btn-primary btn shadow-sm"  %>                  <!-- Button link that leads you to the meal -->
                </div>
            </div>
        </div>
    <%end%>
</div>

<ul class="pagination">
    <li class="page-item">
        <%=link_to 'Previous page', vegan_path(@page_number.to_i - 1), class: "page-link"%>
    </li>
    <li class="page-item">
        <%=link_to 'Next page', vegan_path(@page_number.to_i + 1), class: "page-link"%>
    </li>
</u>

app/views/home/vegetarian.html.erb
<h1>Vegetarian</h1>
<div class="row my-4">
    <!-- get appropiate recipes via API request -->
    <% results = getRecipesByDiet(8, @page_number.to_i, 'vegetarian')%>
    <% recipes = results['results']%>
    <!-- loop through them and produce a card for each -->
    <!-- currently 8 meals displayed in 2 rows and 4 columns -->
    <% recipes.each do |recipe| %>
        <div class="col-3 my-3">                                   
            <div class="card border-3 bg-secondary rounded shadow border-3" style="width:275">                    <!-- CARD INSIDE OF CONTAINER  -->
                <%=image_tag(recipe['image'], :class => "card-img-top", :alt => "recipe_img")%>           <!-- IMAGE INSIDE CARD -->
                <div class="card-body">
                <h5 class="card-title fw-bolder text-light"><%=recipe['title']%></h5>                      <!-- Name of the meal -->
                <%=link_to "View recipe", mealpage_path(recipe['id']), class:"btn btn-primary btn shadow-sm"  %>                  <!-- Button link that leads you to the meal -->
                </div>
            </div>
        </div>
    <%end%>
</div>

<ul class="pagination">
    <li class="page-item">
        <%=link_to 'Previous page', vegetarian_path(@page_number.to_i - 1), class: "page-link"%>
    </li>
    <li class="page-item">
        <%=link_to 'Next page', vegetarian_path(@page_number.to_i + 1), class: "page-link"%>
    </li>
</u>